### PR TITLE
Rename specification.markdown to specification.md

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**
Github detect .md as markdown (as it's official extension) and display without need to clic on the file

### CODE REVIEW

**Comment by dtatut** [comment]
changed to .md as requested

**Comment by MarcAntoine-Arnaud** [comment]
I don't understand why you don't merged it and you've made the same commit...

**Comment by dtatut** [comment]
sorry, my mistake. I hope it's not too much of a problem for you

**Comment by MarcAntoine-Arnaud** [comment]
No no it's not a problem ;-)

**Pull request closed without merging**
